version: "3"
services:
    db-project-dev:
        image: postgres
        container_name: db-project-dev
        environment:
            POSTGRES_PASSWORD: ${DB_PASS}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB}
            DATABASE_URL: ${DB_URL}
        volumes:
            - ./dbdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - puma-network
    project-service-dev:
        container_name: project-service-dev
        environment:
            ENVIRONMENT: dev
        build:
            context: ../${PROJECT_PATH}/
            dockerfile: dev.Dockerfile
        ports:
            - "3000:3000"
        depends_on:
            - db-project-dev
        volumes:
            - ../${PROJECT_PATH}:/app
            - /app/node_modules
        networks:
            - puma-network

networks:
    puma-network: 