version: "3"
services:
    db-project-test:
        image: postgres
        container_name: db-project-test
        environment:
            POSTGRES_PASSWORD: ${DB_PASS}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB}
            DATABASE_URL: ${DB_URL_TEST}
        volumes:
            - ./dbdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - puma-network
    project-service-test:
        container_name: project-service-test
        environment:
            ENVIRONMENT: test
        build:
            context: ../${PROJECT_PATH}/
            dockerfile: test.service.Dockerfile
        ports:
            - "3000:3000"
        depends_on:
            - db-project-test
        volumes:
            - ../${PROJECT_PATH}:/app
            - /app/node_modules
        networks:
            - puma-network

networks:
    puma-network: 